import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, FileText, Scale, AlertTriangle, Gavel, BookOpen, RefreshCw, Ban, CreditCard, Mail } from 'lucide-react';

const sections = [
  {
    icon: BookOpen,
    title: '1. Acceptance of Terms',
    content: [
      {
        text: 'By accessing or using QuesGen ("the Platform"), you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree to these Terms, you may not access or use the Platform. These Terms apply to all users, including students, teachers, school administrators, and visitors.',
      },
      {
        text: 'If you are accessing the Platform on behalf of a school or educational institution, you represent and warrant that you have the authority to bind that organization to these Terms.',
      },
    ],
  },
  {
    icon: FileText,
    title: '2. Description of Services',
    content: [
      {
        text: 'QuesGen is an AI-powered educational platform that provides tools for automated question paper generation, assessment creation, and educational content management. Our services include but are not limited to:',
      },
      {
        text: '• AI-driven question generation across multiple subjects and difficulty levels.\n• Assessment and exam paper creation tools.\n• Student performance tracking and analytics.\n• School and classroom management features.\n• Content customization and curriculum alignment tools.\n• Script evaluation and grading assistance.',
      },
    ],
  },
  {
    icon: Scale,
    title: '3. User Accounts & Responsibilities',
    content: [
      {
        subtitle: 'Account Registration',
        text: 'To access certain features of the Platform, you must register for an account. You agree to provide accurate, current, and complete information during registration and to keep your account information updated.',
      },
      {
        subtitle: 'Account Security',
        text: 'You are responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account or any other breach of security.',
      },
      {
        subtitle: 'User Conduct',
        text: 'You agree not to:\n• Use the Platform for any unlawful purpose or in violation of any applicable laws.\n• Attempt to gain unauthorized access to any part of the Platform or its systems.\n• Interfere with or disrupt the integrity or performance of the Platform.\n• Upload or transmit any viruses, malware, or other harmful code.\n• Use the Platform to generate inappropriate, offensive, or misleading educational content.\n• Share your account credentials with others or allow unauthorized access.\n• Reproduce, duplicate, sell, or resell any part of the Platform without express permission.',
      },
    ],
  },
  {
    icon: Gavel,
    title: '4. Intellectual Property',
    content: [
      {
        subtitle: 'Platform Ownership',
        text: 'The Platform, including its design, code, features, AI models, algorithms, and branding, is the intellectual property of QuesGen and is protected by copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, or create derivative works from any part of the Platform.',
      },
      {
        subtitle: 'User-Generated Content',
        text: 'Content you create using the Platform (e.g., question papers, assessments) remains your intellectual property. However, by using the Platform, you grant QuesGen a non-exclusive, worldwide, royalty-free license to use, store, and process this content for the purpose of providing and improving our services.',
      },
      {
        subtitle: 'AI-Generated Content',
        text: 'Content generated by our AI tools is provided for your educational use. While you may use and distribute AI-generated content within your educational institution, you acknowledge that similar content may be generated for other users and that QuesGen retains the right to use aggregated, anonymized patterns to improve its AI models.',
      },
    ],
  },
  {
    icon: CreditCard,
    title: '5. Payment & Subscriptions',
    content: [
      {
        text: 'Certain features of the Platform may require a paid subscription. By subscribing to a paid plan, you agree to the following:',
      },
      {
        text: '• Subscription fees are billed in advance on a monthly or annual basis.\n• All fees are non-refundable except as required by applicable law or as expressly stated otherwise.\n• We reserve the right to change subscription fees with 30 days prior notice.\n• Failure to pay may result in suspension or termination of your account.\n• You are responsible for all applicable taxes associated with your subscription.',
      },
    ],
  },
  {
    icon: AlertTriangle,
    title: '6. Disclaimers & Limitation of Liability',
    content: [
      {
        subtitle: 'Service Availability',
        text: 'The Platform is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not guarantee that the Platform will be uninterrupted, error-free, or free of harmful components.',
      },
      {
        subtitle: 'AI Content Accuracy',
        text: 'While we strive for accuracy, AI-generated content may contain errors or inaccuracies. Teachers and administrators are responsible for reviewing and validating all AI-generated content before use in assessments or educational settings. QuesGen is not liable for any consequences arising from the use of unverified AI-generated content.',
      },
      {
        subtitle: 'Limitation of Liability',
        text: 'To the maximum extent permitted by law, QuesGen shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the Platform.',
      },
    ],
  },
  {
    icon: Ban,
    title: '7. Termination',
    content: [
      {
        text: 'We reserve the right to suspend or terminate your account and access to the Platform at our sole discretion, without prior notice, for conduct that we believe:',
      },
      {
        text: '• Violates these Terms or any applicable law.\n• Is harmful to other users, third parties, or the business interests of QuesGen.\n• Involves fraudulent, abusive, or unlawful activity.',
      },
      {
        text: 'Upon termination, your right to use the Platform will immediately cease. You may request a copy of your data within 30 days of termination, after which we may delete your data in accordance with our Privacy Policy.',
      },
    ],
  },
  {
    icon: RefreshCw,
    title: '8. Modifications to Terms',
    content: [
      {
        text: 'We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting the updated Terms on the Platform. We will make reasonable efforts to notify users of material changes via email or in-app notifications. Your continued use of the Platform after any modifications constitutes your acceptance of the revised Terms.',
      },
    ],
  },
  {
    icon: Scale,
    title: '9. Governing Law & Dispute Resolution',
    content: [
      {
        text: 'These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which QuesGen operates, without regard to its conflict of law provisions. Any disputes arising out of or relating to these Terms or the Platform shall be resolved through binding arbitration in accordance with applicable arbitration rules, unless you opt out within 30 days of account creation.',
      },
    ],
  },
];

export default function TermsConditionsPage() {
  return (
    <div className="min-h-screen bg-[#000000] text-zinc-100 font-sans selection:bg-blue-500/30">
      {/* Header */}
      <div className="sticky top-0 z-50 bg-[#000000]/80 backdrop-blur-xl border-b border-white/[0.06]">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <Link
            to="/register"
            className="flex items-center gap-2 text-sm text-zinc-400 hover:text-white transition-colors group"
          >
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-0.5 transition-transform" />
            Back to Register
          </Link>
          <Link to="/" className="flex items-center gap-2 group">
            <div className="w-7 h-7 rounded-lg bg-white flex items-center justify-center group-hover:scale-105 transition-transform">
              <div className="w-3.5 h-3.5 bg-black rounded-sm" />
            </div>
            <span className="text-lg font-bold tracking-tight text-white">QuesGen</span>
          </Link>
        </div>
      </div>

      {/* Hero */}
      <div className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-violet-500/[0.03] to-transparent" />
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[600px] bg-violet-500/[0.02] rounded-full blur-3xl" />
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-16 pb-12 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-violet-500/10 border border-violet-500/20 text-violet-400 text-xs font-medium mb-6">
            <Gavel className="w-3.5 h-3.5" />
            Legal Agreement
          </div>
          <h1 className="text-4xl sm:text-5xl font-bold tracking-tight text-white mb-4">
            Terms & Conditions
          </h1>
          <p className="text-lg text-zinc-400 max-w-2xl mx-auto">
            Please read these terms carefully before using QuesGen. By accessing our platform,
            you agree to be bound by these terms and conditions.
          </p>
          <p className="mt-4 text-sm text-zinc-500">
            Last Updated: June 5, 2026 · Effective Immediately
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pb-24">
        <div className="space-y-6">
          {sections.map((section, i) => {
            const Icon = section.icon;
            return (
              <div
                key={i}
                className="bg-[#0a0a0a] rounded-2xl border border-white/[0.06] p-6 sm:p-8 relative overflow-hidden group hover:border-white/[0.1] transition-colors"
              >
                <div className="absolute top-0 left-0 w-full h-px bg-gradient-to-r from-transparent via-white/[0.06] to-transparent" />
                <div className="flex items-start gap-4">
                  <div className="flex-shrink-0 w-10 h-10 rounded-xl bg-violet-500/10 border border-violet-500/20 flex items-center justify-center group-hover:bg-violet-500/15 transition-colors">
                    <Icon className="w-5 h-5 text-violet-400" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <h2 className="text-xl font-semibold text-white mb-4">
                      {section.title}
                    </h2>
                    <div className="space-y-4">
                      {section.content.map((block, j) => (
                        <div key={j}>
                          {block.subtitle && (
                            <h3 className="text-sm font-semibold text-zinc-300 mb-1.5">
                              {block.subtitle}
                            </h3>
                          )}
                          <p className="text-sm leading-relaxed text-zinc-400 whitespace-pre-line">
                            {block.text}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Contact Section */}
        <div className="mt-12 bg-[#0a0a0a] rounded-2xl border border-white/[0.06] p-6 sm:p-8 text-center relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-px bg-gradient-to-r from-transparent via-violet-500/20 to-transparent" />
          <Mail className="w-8 h-8 text-violet-400 mx-auto mb-4" />
          <h2 className="text-xl font-semibold text-white mb-2">
            Need Clarification?
          </h2>
          <p className="text-sm text-zinc-400 max-w-md mx-auto mb-4">
            If you have any questions about these Terms and Conditions, please contact
            our legal team.
          </p>
          <a
            href="mailto:legal@quesgen.com"
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white text-black text-sm font-semibold hover:bg-zinc-200 transition-all"
          >
            <Mail className="w-4 h-4" />
            legal@quesgen.com
          </a>
        </div>

        {/* Footer Links */}
        <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4 text-sm text-zinc-500">
          <Link to="/privacy" className="text-violet-400 hover:text-violet-300 transition-colors">
            Privacy Policy
          </Link>
          <span className="hidden sm:inline">•</span>
          <Link to="/login" className="text-zinc-400 hover:text-white transition-colors">
            Sign In
          </Link>
          <span className="hidden sm:inline">•</span>
          <Link to="/register" className="text-zinc-400 hover:text-white transition-colors">
            Create Account
          </Link>
        </div>
      </div>
    </div>
  );
}
